export default {
    essays: [
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title1: The Elegance of Baseball: Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good",
            aLinkText: "Read more...",
            tags: ["ball", "sports", "olympics"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title2: The Elegance of Football",
            aLinkText: "Read more...",
            tags: ["sports", "world-cup", "health", "baseball", "match", "analytics", "cool", "javascript", "python", "c++", "object oriented programming", "linux", "operating system", "open source project"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title3: The Elegance of Soccer",
            aLinkText: "Read more...",
            tags: ["Game", "america"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title4: The Elegance of Basketball",
            aLinkText: "Read more...",
            tags: ["NBA", "Data", "ball"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title5: The Elegance of Tennis",
            aLinkText: "Read more...",
            tags: ["field", "small", "fast"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title6: The Elegance of Swimming",
            aLinkText: "Read more...",
            tags: ["water", "swim"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title7: The Elegance of Track & Field",
            aLinkText: "Read more...",
            tags: ["field", "track", "olympics", "match"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title8: The Elegance of Olympics",
            aLinkText: "Read more...",
            tags: ["Rio", "2016", "Brazil"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title9: The Elegance of Cycling",
            aLinkText: "Read more...",
            tags: ["mountain", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title10: The Elegance of Parkour",
            aLinkText: "Read more...",
            tags: ["parkour", "dangerous"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title11: The Elegance of Skydiving",
            aLinkText: "Read more...",
            tags: ["extreme", "helicopter", "sky", "cool"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title12: The Elegance of Surfing",
            aLinkText: "Read more...",
            tags: ["water", "match", "health"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title13: The Elegance of Skiing",
            aLinkText: "Read more...",
            tags: ["snow", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title14: The Elegance of Hiking",
            aLinkText: "Read more...",
            tags: ["mountain"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title15: The Elegance of Programming",
            aLinkText: "Read more...",
            tags: ["computer", "data"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title16: The Elegance of Volleyball",
            aLinkText: "Read more...",
            tags: [],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title17: The Elegance of Data",
            aLinkText: "Read more...",
            tags: ["data", "computer", "technology"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "hahfrgaffweasdg",
            aLinkText: "Read more...",
            tags: ["ball", "sports", "olympics"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "erghashtTitle2: The Elegance of Football",
            aLinkText: "Read more...",
            tags: ["sports", "world-cup", "health", "baseball", "match", "analytics", "cool", "javascript", "python", "c++", "object oriented programming", "linux", "operating system", "open source project"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title3: The Erthjdashjrthadhlegance of Soccer",
            aLinkText: "Read more...",
            tags: ["Game", "america"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title4: Theehhdfashrehadh Elegance of Basketball",
            aLinkText: "Read more...",
            tags: ["NBA", "Data", "ball"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title5: The Ehthjadgdasgasgraewlegance of Tennis",
            aLinkText: "Read more...",
            tags: ["field", "small", "fast"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title6: The Eleghagasgagasgraewance of Swimming",
            aLinkText: "Read more...",
            tags: ["water", "swim"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title7: The Elegartyehryewy2535325nce of Track & Field",
            aLinkText: "Read more...",
            tags: ["field", "track", "olympics", "match"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title8: The Elegbbsdvtbn t34v34bg34ance of Olympics",
            aLinkText: "Read more...",
            tags: ["Rio", "2016", "Brazil"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title9: The Eleaneyebgebtyb34ybgance of Cycling",
            aLinkText: "Read more...",
            tags: ["mountain", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title10: The Eleganc5b2b6b245b634b62e of Parkour",
            aLinkText: "Read more...",
            tags: ["parkour", "dangerous"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title11: The Eleganc6b2362b346bb23b6e of Skydiving",
            aLinkText: "Read more...",
            tags: ["extreme", "helicopter", "sky", "cool"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title12: The Elegab426b34b23b36nce of Surfing",
            aLinkText: "Read more...",
            tags: ["water", "match", "health"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title13: The Elegab236b34b6267n6b5bnce of Skiing",
            aLinkText: "Read more...",
            tags: ["snow", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title14: The Elegan62364n262b634n2362bnce of Hiking",
            aLinkText: "Read more...",
            tags: ["mountain"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title15: The Elegatrnetgebtbtrbtvqnce of Programming",
            aLinkText: "Read more...",
            tags: ["computer", "data"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title16: The Elegatnqebrhtqqgvvtnce of Volleyball",
            aLinkText: "Read more...",
            tags: [],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title17: The Elegance otnqewtbhqtqvvqtwef Data",
            aLinkText: "Read more...",
            tags: ["data", "computer", "technology"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title1: The Elegance of Baseball: Baseball is good, Baseball is good, Baseball is good, Baseball is goodbqtbqwtebqwtb, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good, Baseball is good",
            aLinkText: "Read more...",
            tags: ["ball", "sports", "olympics"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title2: The Elegance otqnehbtqvgtgqwgf Football",
            aLinkText: "Read more...",
            tags: ["sports", "world-cup", "health", "baseball", "match", "analytics", "cool", "javascript", "python", "c++", "object oriented programming", "linux", "operating system", "open source project"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title3: The Elegance ofhjgfghqrgregregqer Soccer",
            aLinkText: "Read more...",
            tags: ["Game", "america"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title4: The Elegance otebhyebevyqkykf Basketball",
            aLinkText: "Read more...",
            tags: ["NBA", "Data", "ball"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title5: The Elegance.ipo,ipip,.iop.oip.][p[p[]]] of Tennis",
            aLinkText: "Read more...",
            tags: ["field", "small", "fast"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title6: The Elegartneryn5463754733nce of Swimming",
            aLinkText: "Read more...",
            tags: ["water", "swim"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title7: The Elegance of7h34753g7347g Track & Field",
            aLinkText: "Read more...",
            tags: ["field", "track", "olympics", "match"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title8: The Elegance of O47nj375y2cf62f64f2lympics",
            aLinkText: "Read more...",
            tags: ["Rio", "2016", "Brazil"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title9: The Elegance of264f642f6242f Cycling",
            aLinkText: "Read more...",
            tags: ["mountain", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title10: The Elegance of Parg263g426g3462g432gkour",
            aLinkText: "Read more...",
            tags: ["parkour", "dangerous"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title11: The Elegance of Sg264g26g634g236g4326gkydiving",
            aLinkText: "Read more...",
            tags: ["extreme", "helicopter", "sky", "cool"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title12: The Eleganc2f364f26f436f2e of Surfing",
            aLinkText: "Read more...",
            tags: ["water", "match", "health"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title13: The Elegance ovgwertcvfewrqfrqwcff Skiing",
            aLinkText: "Read more...",
            tags: ["snow", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title14: The Elegance tbqtceqrvervqewrvof Hiking",
            aLinkText: "Read more...",
            tags: ["mountain"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title15: The Elegan3b532532v52v5v32ce of Programming",
            aLinkText: "Read more...",
            tags: ["computer", "data"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title16: The Elegance ofrnybwrtyvywretvw Volleyball",
            aLinkText: "Read more...",
            tags: [],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title17: The Elegance of Da3vt534v52ta",
            aLinkText: "Read more...",
            tags: ["data", "computer", "technology"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "This is a cool title",
            aLinkText: "Read more...",
            tags: ["Rio", "2016", "Brazil"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title9: ThThis is a cool titlee Elegance of264f642f6242f Cycling",
            aLinkText: "Read more...",
            tags: ["mountain", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title10: The ElegThis is a cool titleance of Parg263g426g3462g432gkour",
            aLinkText: "Read more...",
            tags: ["parkour", "dangerous"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title11: The ElegThis is a cool titleance of Sg264g26g634g236g4326gkydiving",
            aLinkText: "Read more...",
            tags: ["extreme", "helicopter", "sky", "cool"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title12: The Eleganc2f3agdsgewwe64f26f436f2e of Surfing",
            aLinkText: "Read more...",
            tags: ["water", "match", "health"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title13: The EThis is a cool titletcvfewrqfrqwcff Skiing",
            aLinkText: "Read more...",
            tags: ["snow", "speed"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title14: ThThis is a cool titletceqrvervqewrvof Hiking",
            aLinkText: "Read more...",
            tags: ["mountain"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title15: The EleganThis is a cool titlece of Programming",
            aLinkText: "Read more...",
            tags: ["computer", "data"],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "Title16: The Elegance ofrnybwrtThis is a cool titleeyball",
            aLinkText: "Read more...",
            tags: [],
            editorAreaShow: false
        },
        {
            author: "Guannan Lyu",
            headImgSrc: require("../assets/head.png"),
            dateInfo: "Aug 7, 2019",
            essayLength: "6 min read",
            thumbnailImgSrc: require("../assets/thumbnail.png"),
            essayTitle: "TitThis is a cool titlegance of Da3vt534v52ta",
            aLinkText: "Read more...",
            tags: ["data", "computer", "technology"],
            editorAreaShow: false
        },
    ],
    queryWord: {
        queryType: "title", // default is searching by "title"
        queryContent: ""
    },
    // First you need to be authorized, then you can toggle the editor mode.
    // If not authorized, then you will not get to the second step of "editor mode".
    // If you are authorized, and you turn on the editor mode, then it's the last step:
    // toggling the editorAreaShow in each essay item. If it's true,
    // then the admin panel shows up, if false then the admin panel disappears.
    isAuthorized: true,
    editorMode: false
}